feat: Use user ID to track the rate limit
arcjet/arcjet-js-example pull request #74
Opened 2024-07-31 21:19 UTC by davidmytton

Add the user ID to the session and use it for tracking the rate limit so that if the limit is hit, you can sign in and get a new limit linked to your session.

2024-08-05 18:00 UTC, blaine-arcjet commented
> you can sign in and get a new limit linked to your session.

I believe you will still be in the block cache. As we've seen in [ben's example](https://github.com/arcjet/arcjet-js/blob/4dac6d5c1f515960b54d215218cdeb5e3030c3f5/examples/nextjs-14-permit/src/lib/arcjet.ts#L8-L9), we need to use something like `fingerprint` as the top-level characteristic and vary it based on login vs ip.

2024-08-05 18:53 UTC, davidmytton commented
When I tested it the block cache seemed to be purged when I logged out, but I've switched it to the method in Ben's example anyway.

2024-08-06 00:20 UTC, blaine-arcjet requested changes
We want to remove the characteristics from the rate limit rules and just use the fingerprint as defined as either the `userId` or `ip`.

2024-08-06 00:20 UTC, blaine-arcjet commented on app/rate-limiting/test/route.ts
> +        characteristics: ["userId"],
```suggestion
```
You'll just want to use the fingerprint

2024-08-06 00:20 UTC, blaine-arcjet commented on app/rate-limiting/test/route.ts
> +  // limit based on their user ID
```suggestion
```

2024-08-06 00:20 UTC, blaine-arcjet commented on app/rate-limiting/test/route.ts
> +    // the IP address to track them
```suggestion
```

2024-08-06 00:20 UTC, blaine-arcjet commented on app/rate-limiting/test/route.ts
> +        characteristics: ["ip.src"],
```suggestion
```

2024-08-06 00:20 UTC, blaine-arcjet commented on app/rate-limiting/test/route.ts
> +    userId: session?.user?.id!,
```suggestion
```

2024-08-07 16:52 UTC, blaine-arcjet approved these changes

2024-08-07 17:12 UTC, merged